### ISSUE TITLE
Try disqus for comments.

### ISSUE THREAD

**Issue by balabhadra** [leapfrogtechnology/zoomify-child#2]

**Comment by prakash014** [comment]
Disqus has now been implemented, we need few more comment moderators.
For that I need to be provided with disqus username of future moderators

**Comment by balabhadra** [comment]
Add me as a moderator bmaharjan@lftechnology.com. You could add yourself as a moderator too. Please ask in the ror hipchat group if anybody wants to moderate comments.

**Comment by balabhadra** [comment]
I didn't see any code committed here for disqus integration. Am I missing something?

**Comment by prakash014** [comment]
disqus provides plugin for the integration, hence we don't need to play around with code

**Comment by balabhadra** [comment]
Great!
